# Generated by Django 5.2.8 on 2025-12-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('critica', 'Crítica'), ('advertencia', 'Advertencia')], max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('nivel_contaminacion', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
