# Generated by Django 5.2.8 on 2025-12-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='estaciones.estacion'),
        ),
    ]
