# Generated by Django 5.2.8 on 2025-12-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ubicacion_latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ubicacion_longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ubicacion_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_certificado', models.FileField(blank=True, null=True, upload_to='certificados_estaciones/')),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
