# Generated by Django 5.2.8 on 2025-12-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('variables', 'Variables Meteorológicas'), ('concentraciones', 'Concentraciones de Material Particulado'), ('todos', 'Variables y Concentraciones')], max_length=20)),
                ('unidad_de_medida', models.CharField(max_length=20)),
                ('fecha_calibracion', models.DateField()),
                ('variables_medibles', models.JSONField(default=list)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='estaciones.estacion')),
            ],
        ),
    ]
