# Generated by Django 5.2.8 on 2025-12-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('velocidad_viento', 'Velocidad Viento'), ('direccion_viento', 'Direccion Viento'), ('humedad', 'Humedad'), ('temperatura', 'Temperatura'), ('NO2', 'No2'), ('PM25', 'Pm25'), ('SO2', 'So2'), ('O3', 'O3'), ('CO', 'Co')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=7)),
                ('fecha_hora', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='sensores.sensor')),
            ],
        ),
    ]
